/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagenmentsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Hospital extends javax.swing.JFrame {

    private int index = -1;
    private Staff staff;
    private StaffOperation operation;

    /**
     * Creates new form Hospital
     */
    public Hospital() {
        initComponents();
        operation = new StaffOperation();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGender = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAddress = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        fmtMN = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        CBstate = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtIC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        RBmale = new javax.swing.JRadioButton();
        RBfemale = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        CBblood = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        txtGName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtGNum = new javax.swing.JTextField();
        BtnAddPatient = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnSearch = new javax.swing.JButton();
        BtnView = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        bill = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDisplay = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOSPITAL MANAGEMENT SYSTEM");

        jLabel3.setText("Patient Name");

        jLabel4.setText("Patient Address");

        taAddress.setColumns(20);
        taAddress.setRows(5);
        jScrollPane1.setViewportView(taAddress);

        jLabel6.setText("Mobile Number");

        fmtMN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##########"))));
        fmtMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fmtMNActionPerformed(evt);
            }
        });

        jLabel7.setText("State");

        CBstate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please Select", "Johor", "Kedah", "Pulau Pinang", "Perlis", "Perak", "Selangor", "Pahang", "Kelantan", "Terengganu", "Melaka", "Negeri Sembilan", "Sabah", "Sarawak" }));
        CBstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBstateActionPerformed(evt);
            }
        });

        jLabel8.setText("IC Number");

        jLabel9.setText("Gender");

        btnGender.add(RBmale);
        RBmale.setText("Male");
        RBmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBmaleActionPerformed(evt);
            }
        });

        btnGender.add(RBfemale);
        RBfemale.setText("Female");

        jLabel10.setText("Blood Type");

        CBblood.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please Select", "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));

        jLabel11.setText("Guardian Name");

        jLabel12.setText("Guardian Mobile Num");

        BtnAddPatient.setText("ADD PATIENT");
        BtnAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddPatientActionPerformed(evt);
            }
        });

        BtnUpdate.setText("UPDATE");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnDelete.setText("DELETE");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnSearch.setText("SEARCH");
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        BtnView.setText("VIEW");
        BtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewActionPerformed(evt);
            }
        });

        BtnReset.setText("RESET");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        BtnExit.setText("EXIT");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });

        jLabel13.setText("Age");

        bill.setText("BILL");
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });

        taDisplay.setColumns(20);
        taDisplay.setRows(5);
        jScrollPane2.setViewportView(taDisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel4)))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPName, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                        .addComponent(txtIC)
                                        .addComponent(txtGName)
                                        .addComponent(txtGNum))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(101, 101, 101)
                                                .addComponent(bill)
                                                .addGap(14, 14, 14)
                                                .addComponent(BtnExit))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel10))
                                                .addGap(73, 73, 73)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(RBmale, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fmtMN, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(RBfemale)
                                                    .addComponent(CBstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(CBblood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)
                                .addContainerGap(185, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAddPatient)
                        .addGap(18, 18, 18)
                        .addComponent(BtnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSearch)
                        .addGap(18, 18, 18)
                        .addComponent(BtnView)
                        .addGap(18, 18, 18)
                        .addComponent(BtnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(BtnReset)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fmtMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtGName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(CBblood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtGNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBmale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RBfemale)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAddPatient)
                    .addComponent(BtnUpdate)
                    .addComponent(BtnDelete)
                    .addComponent(BtnSearch)
                    .addComponent(BtnView)
                    .addComponent(BtnReset)
                    .addComponent(BtnExit)
                    .addComponent(bill))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fmtMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmtMNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmtMNActionPerformed

    private void RBmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBmaleActionPerformed

    private void BtnAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddPatientActionPerformed
        // TODO add your handling code here:
        String name = txtPName.getText();
        String ic = txtIC.getText();
        int age = Integer.parseInt(txtAge.getText());
        String address = taAddress.getText();
        String state = (String) CBstate.getSelectedItem();
        String phone = fmtMN.getText();
        String blood = (String) CBblood.getSelectedItem();
        String gender = null;
        if (RBmale.isSelected()) {
            gender = "Male";
        }

        if (RBfemale.isSelected()) {
            gender = "Female";
        }

        String guardian = txtGName.getText();
        String contact = txtGNum.getText();
        JOptionPane.showMessageDialog(rootPane, "Patient Succesfully Added");
        taDisplay.setText("\nName: " + name + "\nIdentity Card Number: " + ic + "\nAge: " + age + "\nAddress: " + address + "\nMobile Number: " + phone + "\nBlood Group: " + blood + "\nGender: " + gender + "\nGuardian Name: " + guardian + "\nGuardian Number: " + contact + "\n");
        staff = new Staff(name, age, ic, gender, address, state, phone, blood, guardian, contact);

        index++;
        System.out.println("Registeration number = " + index);
        operation.addStaff(staff);


    }//GEN-LAST:event_BtnAddPatientActionPerformed

    private void BtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewActionPerformed
        // TODO add your handling code here:
        String output = operation.readAllStaffs();
        taDisplay.setText(output);
    }//GEN-LAST:event_BtnViewActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_BtnExitActionPerformed

    private void CBstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBstateActionPerformed

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
        // TODO add your handling code here:
        String searchIC = JOptionPane.showInputDialog(null, "IC Number: ");
        String found = operation.searchStaff(searchIC);

        if (found == null) {
            JOptionPane.showMessageDialog(rootPane, "Sorry IC not found");
        } else {
            JOptionPane.showMessageDialog(rootPane, "IC found");
        }
        taDisplay.setText(found);


    }//GEN-LAST:event_BtnSearchActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:

        txtPName.setText("");
        txtIC.setText("");
        txtAge.setText("");
        taAddress.setText("");
        CBstate.setSelectedIndex(0);
        fmtMN.setText(" ");
        CBblood.setSelectedIndex(0);
        RBmale.setSelected(false);
        RBfemale.setSelected(false);
        txtGName.setText("");
        txtGNum.setText("");
        taDisplay.setText("");

        JOptionPane.showMessageDialog(rootPane, "You have successfully reset");

    }//GEN-LAST:event_BtnResetActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
      

            String name = txtPName.getText();
            String ic = txtIC.getText();

            System.out.println("IC = " + ic);

            int age = Integer.parseInt(txtAge.getText());
            String address = taAddress.getText();
            String state = (String) CBstate.getSelectedItem();
            String phone = fmtMN.getText();
            String blood = (String) CBblood.getSelectedItem();
            String gender = null;
            if (RBmale.isSelected()) {
                gender = "Male";
            }

            if (RBfemale.isSelected()) {
                gender = "Female";
            }

            String guardian = txtGName.getText();
            String contact = txtGNum.getText();
            JOptionPane.showMessageDialog(rootPane, "The record successfully updated");
            taDisplay.setText("Name: " + name + "\nIdentity Card Number: " + ic + "\nAge: " + age + "\nAddress: " + address + "\nMobile Number: " + phone + "\nBlood Group: " + blood + "\nGender: " + gender + "\nGuardian Name: " + guardian + "\nGuardian Number: " + contact + "\n");
            staff = new Staff(name, age, ic, gender, address, state, phone, blood, guardian, contact);
            operation.updateStaff(staff);
        
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        String searchIC = JOptionPane.showInputDialog(null, "IC Number that you want to delete: ");
        String found = operation.deleteStaff(searchIC);

        if (found == null) {
            JOptionPane.showMessageDialog(rootPane, "Sorry, the record has been deleted");
        } else {
            JOptionPane.showMessageDialog(rootPane, "The record successfully deleted");
        }
        taDisplay.setText(found);


    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        String searchIC = JOptionPane.showInputDialog(null, "IC Number: ");
        String found = operation.deleteStaff(searchIC);

        if (found == null) {
            JOptionPane.showMessageDialog(rootPane, "Sorry, invalid IC");
        } else {
            bill Bill = new bill();
            Bill.setVisible(true);
        }


    }//GEN-LAST:event_billActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddPatient;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnSearch;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JButton BtnView;
    private javax.swing.JComboBox CBblood;
    private javax.swing.JComboBox CBstate;
    private javax.swing.JRadioButton RBfemale;
    private javax.swing.JRadioButton RBmale;
    private javax.swing.JButton bill;
    private javax.swing.ButtonGroup btnGender;
    private javax.swing.JFormattedTextField fmtMN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taAddress;
    private javax.swing.JTextArea taDisplay;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtGName;
    private javax.swing.JTextField txtGNum;
    private javax.swing.JTextField txtIC;
    private javax.swing.JTextField txtPName;
    // End of variables declaration//GEN-END:variables
}
